paths:
  uploads: uploads
  data: _data
  layouts: _layouts
  includes: _includes
collections_config:
  data:
    path: _data
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    output: true
    filter: strict
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  products:
    path: _products
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  customers:
    path: _customers
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_inputs:
  categories:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
  tags:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
_select_data: {}
_structures: {}
_editables:
  content:
    image_size_attributes: true
    resize_style: contain
data_config: {}
timezone: Etc/UTC
