paths:
  uploads: uploads
  data: _data
  layouts: _layouts
  includes: _includes
collections_config:
  data:
    path: _data
    output: false
    icon: notes
    _editables: {}
    _inputs: {}
    _select_data: {}
    _structures: {}
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      post:
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
        _editables: {}
        _inputs: {}
        _select_data: {}
        _structures: {}
  pages:
    output: true
    filter: strict
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  products:
    path: _products
    output: false
    icon: notes
    _editables: {}
    _inputs:
      background_color:
        type: color
        options:
          format: hex
          alpha: true
        label: Background Color
        cascade: true
    _select_data: {}
    _structures: {}
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas: {}
  customers:
    path: _customers
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_inputs:
  categories:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
  tags:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
  highlight_color:
    type: color
    cascade: true
_select_data: {}
_structures:
  example:
    style: select
    values:
      - {}
_editables: {}
data_config: {}
timezone: Etc/UTC
